### PR TITLE
Create FreeTether.fc

### PR DESCRIPTION
**Pull request by sunk818**
Win up to $300 worth of Tether tokens (USDT) every hour. Instant withdrawls and very low minimum threshold.

### CODE REVIEW

**Comment by sunk818** [comment]
Let me know if the description and the ref url in the code needs to be revised.

**Review by aviramdayan — COMMENTED** [review]
tnx but we have all in one here - coinfaucet
https://faucetcollector.com/faucets/details/a2ff21535977440c9cb69caca62aa136

https://github.com/Faucet-Collector/scripts/blob/6355cb2fdaa7b987417d41622b247ae3e53249bf/Coinfaucet/Coinfaucets.fc

**Comment by sunk818** [comment]
You have all in one, but can you actually visit all of them, or just one?

**Comment by aviramdayan** [comment]
`
You have all in one, but can you actually visit all of them, or just one?
`
nope the script not does the all at once
you can duplicate the script and after you can choose favorite coin

**Pull request closed without merging**
